### ISSUE TITLE
 Two types of Errors when generating tensors 

### ISSUE THREAD

**Issue by chenludi** [gersteinlab/ThermoNet#3] opened 2022-03-25 06:14 UTC
Hello,

Thank you for sharing all the source code and writing a nice manual! I've been running ThermoNet to predict protein stability changes for many proteins but these errors happened to a small number of them. I am wondering if you could help me figure out why the following two types of errors happened and how to solve them. 
**Error1 at the step of prepareProteinForAtomtyping**
I attached the original pdb file I applied for the first step and the *_relaxed.pdb file I got from previous steps.
`
Now computing features for: 
dir/Q96EK7_A/Q96EK7_A/Q96EK7_A_relaxed.pdb
Traceback (most recent call last):
  File "dir/ThermoNet/ThermoNet/gends.py", line 120, in <module>
    main()
  File "dir/ThermoNet/ThermoNet/gends.py", line 77, in main
    voxelsize=args.voxelsize, verbose=args.verbose, rotations=rotations)
  File "dir/ThermoNet/ThermoNet/utils/pdb_utils.py", line 369, in compute_voxel_features
    prot = prepareProteinForAtomtyping(mol, verbose=verbose)
  File "dir/condaenv/py36/lib/python3.6/site-packages/moleculekit/tools/atomtyper.py", line 146, in prepareProteinForAtomtyping
    resnames
RuntimeError: Found atoms with resnames ['PRO'] in the Molecule which can cause issues with the voxelization. Please make sure to only pass protein atoms and metals.
`
Error2:
I attached the original pdb file I applied for the first step and the *_relaxed.pdb file I got from previous steps.
`2022-03-24 09:22:13,025 - propka - INFO - No pdbfile provided
2022-03-24 09:22:42,770 - numexpr.utils - INFO - Note: detected 96 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2022-03-24 09:22:42,771 - numexpr.utils - INFO - Note: NumExpr detected 96 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
Now computing features for: 
dir/P35749_A/P35749_A/P35749_A_relaxed.pdb
[ThermoNet_gends_errors.zip](https://github.com/gersteinlab/ThermoNet/files/8347928/ThermoNet_gends_errors.zip)

==============================
*** Open Babel Warning  in PerceiveBondOrders
  Failed to kekulize aromatic bonds in OBMol::PerceiveBondOrders (title is /tmp/tmpgin5lx3e.pdb)
`
I am looking forward to your reply. Thank you for your time in advance!

Best,
Chenlu

**Comment by computbiolgeek** [comment] 2022-03-26 23:05
Hi Chenlu,

Thanks for your interest in this work. For error 1, it looks like it has to do with some atom type in prolines that the MoleculeKit package does not recognize as protein atom, according to the source code here: https://github.com/Acellera/moleculekit/blob/main/moleculekit/tools/atomtyper.py, line 146.  However, I looked into the PDB files you attached and couldn't find anything wrong with the prolines. It also appears to me that the PDB file corresponds to some AlphaFold predicted structure, did other structures from AlphaFold run OK with ThermoNet?  For error 2, I actually do not understand what it is. Can you provide more information?

Best,
Bian

**Comment by chenludi** [comment] 2022-03-29 02:57
Hi Bian,

Thank you for the fast response! 

For error 1, it also returns errors with other amino acids in addition to prolines, e.g. ASN, ARG... and for other AlphaFold structures. I am wondering if it has something to do with the protein itself, e.g. special structure that makes the MoleculeKit package fails in parsing it correctly? I looked at a dozen of the protein structures and couldn't find anything obviously wrong in these AlphaFold models. However, I don't have much experience working on protein structures and I'd like to send you more examples if it will help.

For error 2, I attached the whole output for your reference. 

Overall, error1 and error2 together, happened in ~2% AlphaFold predicted structures that I applied.

Thank you!

Best,
Chenlu

[error2.txt](https://github.com/gersteinlab/ThermoNet/files/8367691/error2.txt)

**Comment by chenludi** [comment] 2022-04-27 01:53
Hi Bian,

This is an update about the errors I encountered. 

Only the error "Found atoms with resnames ['PRO'] in the Molecule which can cause issues with the voxelization. Please make sure to only pass protein atoms and metals." will result 100% failure for all mutations. This is not limited to PRO. I saw report on other amino acids.

ThermoNet will make prediction regardless of seeing the second error. 

Best,
Chenlu

**Comment by computbiolgeek** [comment] 2022-05-14 05:11
Closing the issue here, because the issue was later found to be caused by corrupted protein structures, for example, non-standard bond lengths and angles in amino acid side chains. Such corrupted bonds can't be recognized by the VMD atom parser used in the MoleculeKit package.

**Closed as completed by computbiolgeek** 2022-05-14 05:11 UTC
